Added requirements.txt and update the readme to inclue it
opendxl-community/OpenDXL-QChat pull request #1
Opened 2017-07-12 21:51 UTC by tmcdonal-mcafee

2017-07-13 21:03 UTC, PoesRaven approved these changes

2017-07-13 21:04 UTC, PoesRaven commented on README.md
> +Qchat only supports Linux Desktop systems.
QChat uses appJar which is platform independent. I've tested with Linux, Mac, and Windows.

2017-07-13 21:06 UTC, PoesRaven commented on README.md
> +QChat (Quick Chat) is a chat room service for Linux Desktop systems leveraging the OpenDXL event invokation capabilities to create small, light-weight, and interactive chat rooms for use by incident
This has been tested with Linux, Windows, and Mac.

2017-07-13 21:07 UTC, PoesRaven requested changes
QChat uses appJar which is platform independent. I've tested with Windows, Linux, and Mac.

2017-07-13 21:13 UTC, tmcdonal-mcafee commented on README.md
> +Qchat only supports Linux Desktop systems.
Ah, sorry, the dependency on curses is why I thought it was only supporting Linux. What library are you using in Windows to satisfy the curses dependency?

2017-07-14 14:38 UTC, PoesRaven commented on README.md
> +Qchat only supports Linux Desktop systems.
The curses import has been removed and code updated to reflect. It was antiquated pre appJar implementation.

2017-07-14 17:53 UTC, PoesRaven requested changes
Please update te reflect platform before merging.

2017-07-14 21:51 UTC, tmcdonal-mcafee commented
I've updated the documentation to remove the references to Linux.

2017-07-18 03:12 UTC, merged